[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "polars-qlens"
version = "0.1.2"
description = "Data quality profiling and analysis for Python."
readme = "README.md"
requires-python = ">=3.12"

authors = [
    { name = "Rekik Samson", email = "rekiksamson5@gmail.com" }
]

license = "MIT"
license-files = ["LICENSE"]

keywords = [
    "data-quality",
    "data-profiling",
    "data-analysis",
    "polars",
    "data-validation"
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent"
]

dependencies = [
    "polars>=1.0",
    "numpy>=2.0"
]

[project.urls]
Homepage = "https://github.com/rcodes-ix/polars-qlens"
Repository = "https://github.com/rcodes-ix/polars-qlens"
Issues = "https://github.com/rcodes-ix/polars-qlens/issues"

[tool.setuptools.packages.find]
where = ["src"]